apiVersion: v1
kind: Service
metadata:
  name: sl-boutique-shippingservice
spec:
  ports:
    - name: c-http
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: d-http
      port: 50052
      targetPort: 50052
      protocol: TCP
  selector:
    app.kubernetes.io/name: sl-boutique-shippingservice
  type: ClusterIP
