apiVersion: apps/v1
kind: Deployment
metadata:
  name: sl-boutique-emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sl-boutique-emailservice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: sl-boutique-emailservice
    spec:
      containers:
        - image: 159616352881.dkr.ecr.eu-west-1.amazonaws.com/microservices-demo-emailservice:latest
          name: b-emailservice
          imagePullPolicy: Always
          resources: {}
          ports:
            - name: c-http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SHIPPING_SERVICE_ADDR
              value: "sl-boutique-shipping:50051"   
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "sl-boutique-productcatalog:3550" 
            - name: CART_SERVICE_ADDR
              value: "sl-boutique-cart:7070"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "sl-boutique-recommendation:8080"                
            - name: CURRENCY_SERVICE_ADDR
              value: "sl-boutique-currency:7000"
            - name: EMAIL_SERVICE_ADDR
              value: "sl-boutique-email:8080"
            - name: CHECKOUT_SERVICE_ADDR
              value: "sl-boutique-checkout:5050"
            - name: AD_SERVICE_ADDR
              value: "sl-boutique-ad:9555" 
            - name: PAYMENT_SERVICE_ADDR
              value: "sl-boutique-payment:50051" 
