apiVersion: apps/v1
kind: Deployment
metadata:
  name: sl-boutique-checkoutservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sl-boutique-checkoutservice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: sl-boutique-checkoutservice
    spec:
      containers:
        - image: 159616352881.dkr.ecr.eu-west-1.amazonaws.com/microservices-demo-checkoutservice:latest
          name: checkoutservice
          imagePullPolicy: Always
          resources: {}
          ports:
            - name: c-http
              containerPort: 5050
              protocol: TCP
          env:
            - name: SHIPPING_SERVICE_ADDR
              value: "sl-boutique-shippingservice:50051"   
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "sl-boutique-productcatalog:3550" 
            - name: CART_SERVICE_ADDR
              value: "sl-boutique-cartservice:7070"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "sl-boutique-recommendationservice:8080"                
            - name: CURRENCY_SERVICE_ADDR
              value: "sl-boutique-currencyservice:7000"
            - name: EMAIL_SERVICE_ADDR
              value: "sl-boutique-emailservice:8080"
            - name: CHECKOUT_SERVICE_ADDR
              value: "sl-boutique-checkoutservice:5050"
            - name: AD_SERVICE_ADDR
              value: "sl-boutique-adservice:9555" 
            - name: PAYMENT_SERVICE_ADDR
              value: "sl-boutique-paymentservice:50051"                       
