apiVersion: apps/v1
kind: Deployment
metadata:
  name: sl-boutique-notificationsender
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sl-boutique-notificationsender
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: sl-boutique-notificationsender
    spec:
      imagePullSecrets:
        - name: aws-secret
      containers:
        - image: 474620256508.dkr.ecr.us-east-2.amazonaws.com/microservices-demo-notificationsender:v0.0.8
          name: sl-boutique-notificationsender
          imagePullPolicy: Always
          resources: {}
          ports:
            - name: sl-sender
              containerPort: 7080
              protocol: TCP
          env:
            - name: SHIPPING_SERVICE_ADDR
              value: "sl-boutique-shippingservice:50051"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "sl-boutique-productcatalog:3550"
            - name: CART_SERVICE_ADDR
              value: "sl-boutique-cartservice:7070"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "sl-boutique-recommendationservice:8080"
            - name: CURRENCY_SERVICE_ADDR
              value: "sl-boutique-currencyservice:7000"
            - name: EMAIL_SERVICE_ADDR
              value: "sl-boutique-emailservice:8080"
            - name: CHECKOUT_SERVICE_ADDR
              value: "sl-boutique-checkoutservice:5050"
            - name: AD_SERVICE_ADDR
              value: "sl-boutique-adservice:9555"
            - name: PAYMENT_SERVICE_ADDR
              value: "sl-boutique-paymentservice:50051"
            - name: OTEL_AGENT_COLLECTOR_PROTOCOL
              value: "http"
            - name: OTEL_AGENT_COLLECTOR_PORT
              value: "443"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=notificationservice,service.version=1.0.0"
            - name: AWS_SQS_QUEUE_URL
              value: "https://sqs.us-east-2.amazonaws.com/474620256508/EmailQueue"
            - name: AWS_REGION
              value: "us-east-2"
            - name: SQS_WAIT_TIME_SEC
              value: "2"
            - name: SQS_MAX_MESSAGES
              value: "1"
            - name: AWS_US_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-settings-access-key
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_US_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-settings-secret
                  key: AWS_SECRET
