apiVersion: apps/v1
kind: Deployment
metadata:
  name: sl-boutique-adservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sl-boutique-adservice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: sl-boutique-adservice
    spec:
      imagePullSecrets:
        - name: aws-secret
      containers:
        - image: 474620256508.dkr.ecr.us-east-2.amazonaws.com/microservices-demo-adservice:v0.0.33
          name: adservice
          imagePullPolicy: Always
          resources: {}
          ports:
            - name: c-http
              containerPort: 9555
              protocol: TCP
          env:
            - name: SHIPPING_SERVICE_ADDR
              value: "sl-boutique-shippingservice:50051"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "sl-boutique-productcatalog:3550"
            - name: CART_SERVICE_ADDR
              value: "sl-boutique-cartservice:7070"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "sl-boutique-recommendationservice:8080"
            - name: CURRENCY_SERVICE_ADDR
              value: "sl-boutique-currencyservice:7000"
            - name: EMAIL_SERVICE_ADDR
              value: "sl-boutique-emailservice:8080"
            - name: CHECKOUT_SERVICE_ADDR
              value: "sl-boutique-checkoutservice:5050"
            - name: AD_SERVICE_ADDR
              value: "sl-boutique-adservice:9555"
            - name: PAYMENT_SERVICE_ADDR
              value: "sl-boutique-paymentservice:50051"
