
name: Merge pull request
on:
  check_run:
    types: [completed]
    #repository_dispatch:
    #branches: [ master ]  
jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    steps:         
      - name: Test
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}                   
        run: |
          echo "$GITHUB_CONTEXT"

 
