
name: Execute e2e tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  K3S_MAX_RETRY_COUNT: ${{ secrets.K3S_MAX_RETRY_COUNT }}
  SLEEP_DURATION: 10
  
jobs:
  trigger_e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - uses: actions/checkout@v3
      
      - name: Set up k3s
        uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest' 
          
      - name: Deploy services
        run: |
          kubectl create secret docker-registry aws-secret --docker-server=159616352881.dkr.ecr.eu-west-1.amazonaws.com --docker-username=AWS --docker-password=$(aws ecr get-login-password)          
          kubectl apply -R -f ./k3s/                      
          
      - name: Wait for fetching containers
        run: |
          chmod +rx ./k3s-deployment/wait-for-pods-statuses.sh          
          ./k3s-deployment/wait-for-pods-statuses.sh $K3S_MAX_RETRY_COUNT $SLEEP_DURATION
          
      - name: Wait for pods to be ready
        run: |
          chmod +rx ./k3s-deployment/wait-for-pods-phases.sh          
          ./k3s-deployment/wait-for-pods-phases.sh $K3S_MAX_RETRY_COUNT $SLEEP_DURATION
          
      - name: Fetch deployment repo
        run: |             
             export GITHUB_TOKEN=
             echo $GITHUB_TOKEN >> token.txt
             git clone https://$GITHUB_TOKEN@github.com/Sealights/microservices-demo-tests.git tests
             git remote set-url origin https://$GITHUB_TOKEN@github.com/Sealights/microservices-demo-tests.git
             
      - name: Install testing tools     
        run: |             
             cd tests             
             npm install
             
      - name: Wait for external IPs
        run: |           
              iterator=1

              while [ $iterator -le $((K3S_MAX_RETRY_COUNT)) ] 
              do
               loadBnalancerStatus=`kubectl get svc sl-boutique-frontend -o json| jq -r .status.loadBalancer`

               if [ ! "$loadBnalancerStatus" == "{}" ]; then
                 echo "$loadBnalancerStatus" > loadBnalancerStatus.json
                 export BOUTIQUE_FRONTEND_IP=`jq -r .ingress[].ip loadBnalancerStatus.json`

                 if [ ! -z "$BOUTIQUE_FRONTEND_IP" ]; then
                   break
                 fi               
               fi

               echo "Retrying... $iterator of $maxIterations"
               iterator=$((iterator+1))
               sleep $((SLEEP_DURATION))
              done

              echo "Frontend IP: $BOUTIQUE_FRONTEND_IP"
              ping $BOUTIQUE_FRONTEND_IP -c 5
               
#      - name: Test Frontend availability
#        run: |
#             ping $BOUTIQUE_FRONTEND_IP -c 5
               
      - name: Run e2e tests     
        run: |                           
             export TEST_ENDPOINT=http://$BOUTIQUE_FRONTEND_IP:8080
             echo "Test entry point: $TEST_ENDPOINT"
             
             cd tests
             npm run test
