
name: Execute e2e tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  #GITHUB_USERNAME: ${{ secrets.GH_USER_NAME }}
  #GITHUB_USER_EMAIL: ${{ secrets.GH_USER_EMAIL }}
  
jobs:
  trigger_e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - uses: actions/checkout@v3
      
      - name: Set up k3s
        #uses: nolar/setup-k3d-k3s@v1
        #with:
        #  github-token: ${{ secrets.GH_PAT }}
        #  k3d-name: sl-boutique
        uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest' 
          
      - name: Test ECR        
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: microservices-demo-checkoutservice
          IMAGE_TAG: latest
        run: |
          echo $ECR_REGISTRY
          echo $ECR_REPOSITORY
          
      - name: Deploy services
        run: |
          #curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          #unzip awscliv2.zip
          #sudo ./aws/install
          #aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 159616352881.dkr.ecr.eu-west-1.amazonaws.com
          #kubectl apply -R -f ./k3s/                      
          kubectl apply -f ./k3s/ad/manifest-pod.yaml
          sleep 15s
          #kubectl get pods
          kubectl describe pod sl-boutique-adservice
          #echo `kubectl get services`          
          
      - name: Deployment repo fetch     
        run: |             
             #git config --global user.name $GITHUB_USERNAME
             #git config --global user.email $GITHUB_USER_EMAIL
             export GITHUB_TOKEN=
             echo $GITHUB_TOKEN >> token.txt
             #gh auth login --with-token < token.txt
             git clone https://$GITHUB_TOKEN@github.com/Sealights/microservices-demo-tests.git tests
             git remote set-url origin https://$GITHUB_TOKEN@github.com/Sealights/microservices-demo-tests.git
             cd tests             
             #npm install
             
             #while [ $counter -le 10 ]
             #do
             #  echo $counter
             #  ((counter++))
             #done

             sleep 30s
             #echo `kubectl get svc sl-boutique-frontend -o json`
             #echo `kubectl get services`
             export BOUTIQUE_FRONTEND_IP=`kubectl get svc sl-boutique-frontend -o json| jq -r .status.loadBalancer.ingress[].ip`         
             echo $BOUTIQUE_FRONTEND_IP
             export TEST_ENDPOINT=http://$BOUTIQUE_FRONTEND_IP:8080
             echo $TEST_ENDPOINT
             kubectl get svc
             kubectl get pods
             ping $BOUTIQUE_FRONTEND_IP -c 5
             wget $TEST_ENDPOINT -t 1             
             #echo `cat index.html'
             #npm run test
