
name: Execute e2e tests
on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  #K3S_MAX_RETRY_COUNT: ${{ secrets.K3S_MAX_RETRY_COUNT }}
  K3S_MAX_RETRY_COUNT: 10
  SLEEP_DURATION: 10
  
jobs:
  trigger_e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - uses: actions/checkout@v3
      
      - name: Set up k3s
        uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest' 
          
      - name: Deploy services
        run: |
          kubectl create secret docker-registry aws-secret --docker-server=159616352881.dkr.ecr.eu-west-1.amazonaws.com --docker-username=AWS --docker-password=$(aws ecr get-login-password)          
          kubectl apply -R -f ./k3s/                      
          
      - name: Wait for fetching containers
        run: |
          chmod +rx ./k3s-deployment/wait-for-pods-statuses.sh          
          ./k3s-deployment/wait-for-pods-statuses.sh $K3S_MAX_RETRY_COUNT $SLEEP_DURATION
          
      - name: Wait for pods
        run: |
          chmod +rx ./k3s-deployment/wait-for-pods-phases.sh          
          ./k3s-deployment/wait-for-pods-phases.sh $K3S_MAX_RETRY_COUNT $SLEEP_DURATION
          
      - name: Fetch deployment repo
        run: |             
             export GITHUB_TOKEN=
             echo $GITHUB_TOKEN >> token.txt
             git clone https://$GITHUB_TOKEN@github.com/Sealights/microservices-demo-tests.git tests
             git remote set-url origin https://$GITHUB_TOKEN@github.com/Sealights/microservices-demo-tests.git
             
      - name: Install testing tools     
        run: |             
             cd tests             
             npm install
             
      - name: Wait for external IPs
        run: |           
            chmod +rx ./k3s-deployment/wait-for-external-ip.sh        
            ./k3s-deployment/wait-for-external-ip.sh $K3S_MAX_RETRY_COUNT $SLEEP_DURATION
            
            kubectl get svc
               
      - name: Test Frontend availability
        run: |
             export BOUTIQUE_FRONTEND_IP=$(cat test-entrypoint.txt)             
             ping $BOUTIQUE_FRONTEND_IP -c 5
               
      - name: Run e2e tests     
        run: |
             export BOUTIQUE_FRONTEND_IP=$(cat test-entrypoint.txt)                          
             echo "TEST: $BOUTIQUE_FRONTEND_IP"
             export TEST_ENDPOINT=http://$BOUTIQUE_FRONTEND_IP:8080
             echo "Test entry point: $TEST_ENDPOINT"
                         
             kubectl get services
             kubectl get pods
                                     
             cd tests
             npm run test
             
      - name: Get logs
        if: always()
        run: | 
             kubectl logs deployment/sl-boutique-paymentservice
